name: kungfauxpandas
channels:
  - defaults
dependencies:
  - python==3.6.*
  - cython=0.28.2
  - django>=2.0.10,>=2.1.5
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - numpy=1.14.3
  - pandas=0.23.0
  - pip=18.1
  - psycopg2=2.7.5
  - pytest=3.5.1
  - scikit-learn>=0.19.1,<0.20
  - scipy=1.1.0
  - seaborn=0.9.0
  - sqlparse=0.2.4
  - statsmodels=0.9.0
  - pip:
    - hug==2.4.0
