name: kungfauxpandas
channels:
  - defaults
dependencies:
  - attrs=18.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=2.1.3
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - cycler=0.10.0
  - cython=0.28.2
  - dbus=1.13.2
  - decorator=4.3.0
  - django=2.0.5
  - entrypoints=0.2.3
  - expat=2.2.5
  - freetype=2.8
  - gettext=0.19.8.1
  - glib=2.56.1
  - html5lib=1.0.1
  - icu=58.2
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.*
  - libiconv=1.15
  - libpng=1.6.34
  - libsodium=1.0.16
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - more-itertools=4.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.5.0
  - numpy=1.14.3
  - numpy-base=1.14.3
  - openssl=1.0.2o
  - pandas=0.23.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.2.0
  - patsy=0.5.0
  - pcre=8.42
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - pluggy=0.6.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - py=1.5.3
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pytest=3.5.1
  - python=3.6.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - pyzmq=17.0.0
  - qt=5.9.5
  - qtconsole=4.3.1
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=39.1.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.23.1
  - sqlparse=0.2.4
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.2.1
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - chardet==3.0.4
    - falcon==1.4.1
    - hug==2.4.0
    - idna==2.6
    - python-mimeparse==1.6.0
    - requests==2.18.4
    - urllib3==1.22
