name: kungfauxpandas
channels:
  - defaults
dependencies:
  - chardet=4.0.0
  - cython=0.29.30
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - numpy=1.23.1
  - pandas=1.4.3
  - pip=22.1.2
  - psycopg2=2.8.6
  - pytest=7.1.2
  - python=3.9.*
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - sqlparse=0.4.1
  - statsmodels=0.13.2
  - pip:
    - hug==2.6.1
