name: kungfauxpandas
channels:
  - defaults
dependencies:
  - cython=0.28.2
  - django=2.0.5
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - numpy=1.14.3
  - pandas=0.23.0
  - pip=10.0.1
  - psycopg2=2.7.5
  - pytest=3.5.1
  - python=3.6.5
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - sqlite=3.23.1
  - sqlparse=0.2.4
  - statsmodels=0.9.0
  - pip:
    - chardet==3.0.4
    - falcon==1.4.1
    - hug==2.4.0
    - idna==2.6
    - python-mimeparse==1.6.0
    - requests==2.18.4
    - urllib3==1.22
